#ifndef DMS_RESOURCE_RUNTIME_H
#define DMS_RESOURCE_RUNTIME_H
#include <stdint.h>
#include "dms_scene.h"

/* Internal descriptors generated by dmsres and consumed by libdms.
   User code normally includes generated resources.h instead. */

/* P1.2 legacy sprite descriptor. Kept ABI/source-compatible with the existing
   GCC demos and older projects that define src/resources.c by hand. */
typedef struct {
    const uint8_t *tiles;
    const uint16_t *palette;
    uint16_t tile_count;
    uint8_t width;
    uint8_t height;
    uint8_t palette_id;
    uint8_t priority;
} DmsSpriteResourceDesc;

#define DMS_SPR_CELL_HFLIP 0x01u
#define DMS_SPR_CELL_VFLIP 0x02u

typedef struct {
    int16_t x, y;              /* cell top-left in frame pixels */
    uint16_t tile;             /* local DRES tile id */
    uint8_t palette;           /* local DRES palette id */
    uint8_t flags;             /* DMS_SPR_CELL_* */
} DmsSpriteCellDesc;

typedef struct {
    uint16_t first_cell;
    uint16_t cell_count;
    int16_t pivot_x, pivot_y;
    int16_t body_x, body_y, body_w, body_h; /* frame-local box, V0.3 hitbox used as BODY */
    uint16_t duration_ticks;   /* 60 Hz ticks, >=1 */
} DmsSpriteFrameDesc;

typedef struct {
    uint16_t first_frame_index;
    uint16_t frame_count;
} DmsSpriteAnimationDesc;

typedef struct {
    uint16_t resource_id;
    const uint8_t *tiles;
    const uint16_t *palettes;  /* palette_count x 16 RGB333 words */
    const DmsSpriteCellDesc *cells;
    const DmsSpriteFrameDesc *frames;
    const uint16_t *animation_frame_ids;
    const DmsSpriteAnimationDesc *animations;
    uint16_t tile_count;
    uint16_t cell_count;
    uint16_t frame_count;
    uint16_t animation_count;
    uint16_t max_frame_cells;
    uint8_t palette_count;
    uint8_t palette_base;
    uint8_t priority;
} DmsDresResourceDesc;

typedef struct {
    uint16_t resource_id;
    const uint8_t *tiles;
    const uint16_t *palettes;
    const uint8_t *palette_ids;
    uint16_t tile_count;
    uint8_t palette_count;
    const uint16_t *tilemap;      /* frozen VDP words, local tile ids */
    uint16_t tilemap_count;
    uint16_t width_cells;
    uint16_t height_cells;
} DmsImageResourceDesc;

typedef struct {
    uint16_t resource_id;
    const uint16_t *bg_a;
    const uint16_t *bg_b;
    uint16_t width_cells;
    uint16_t height_cells;
    uint8_t mode;
    uint16_t tileset_resource_id;
    uint16_t bg_b_image_resource_id; /* optional full-screen/static DIMG */
} DmsMapResourceDesc;

#define DMS_COLL_SOLID      0u
#define DMS_COLL_ONE_WAY    1u
#define DMS_COLL_DANGER     2u
#define DMS_COLL_TRIGGER    6u
#define DMS_COLL_EXIT       7u
#define DMS_COLL_CHECKPOINT 8u

typedef struct {
    uint16_t id;
    uint8_t type;
    uint8_t target_mask;
    uint8_t flags; /* bit0 active, bit1 action, bit2 once */
    int16_t x0, y0, x1, y1;
} DmsCollisionZoneDesc;

typedef struct {
    uint16_t resource_id;
    const DmsCollisionZoneDesc *zones;
    uint16_t zone_count;
    uint16_t width_px, height_px;
} DmsCollisionResourceDesc;

#define DMS_ACT_COND_ALWAYS       0u
#define DMS_ACT_COND_INPUT_X      1u
#define DMS_ACT_COND_BUTTON       2u
#define DMS_ACT_COND_VELOCITY_Y   3u
#define DMS_ACT_COND_ON_GROUND    4u
#define DMS_ACT_COND_NOT_GROUND   5u
#define DMS_ACT_COND_TIME_STATE   6u
#define DMS_ACT_COND_ANIM_DONE    7u
#define DMS_ACT_COND_PLAYER_DISTANCE 8u
#define DMS_ACT_COND_VELOCITY_X   9u
#define DMS_ACT_COND_HIT_WALL     10u
#define DMS_ACT_COND_HIT_CEILING  11u
#define DMS_ACT_COND_HP            12u
#define DMS_ACT_COND_BUTTON_RELEASED 13u
#define DMS_ACT_COND_PLAYER_DISTANCE_X 14u
#define DMS_ACT_COND_PLAYER_DISTANCE_Y 15u
#define DMS_ACT_COND_BUTTON_HELD 16u
#define DMS_ACT_OP_EQ 0u
#define DMS_ACT_OP_NE 1u
#define DMS_ACT_OP_LT 2u
#define DMS_ACT_OP_LE 3u
#define DMS_ACT_OP_GT 4u
#define DMS_ACT_OP_GE 5u
#define DMS_ACT_ACTION_NONE 0u
#define DMS_ACT_ACTION_JUMP 1u
#define DMS_ACT_AI_NONE     0u
#define DMS_ACT_AI_PATROL   1u
#define DMS_ACT_AI_CHASE    2u
#define DMS_ACT_AI_SHMUP    3u
#define DMS_ACT_AI_BOSS     4u
#define DMS_ACT_AI_NPC      5u
#define DMS_ACT_AI_RPG      6u
#define DMS_ACT_AI_TURN_WALL 0x01u
#define DMS_ACT_AI_TURN_EDGE 0x02u
#define DMS_ACT_AI_FOLLOW_X  0x04u
#define DMS_ACT_AI_FOLLOW_Y  0x08u
#define DMS_ACT_PROJECTILE_TOWARD_PLAYER 0x01u
#define DMS_ACT_PROJECTILE_DESTROY_HIT   0x02u
#define DMS_ACT_STATE_INVULNERABLE       0x01u
#define DMS_ACT_STATE_INTANGIBLE         0x02u
#define DMS_ACT_STATE_LOCK_DIRECTION     0x04u
#define DMS_ACT_MOVE_NONE         0u
#define DMS_ACT_MOVE_HORIZONTAL   1u
#define DMS_ACT_MOVE_VERTICAL     2u
#define DMS_ACT_MOVE_FREE_2D      3u
#define DMS_ACT_MOVE_4_DIR        4u
#define DMS_ACT_MOVE_8_DIR        5u
#define DMS_ACTOR_GROUP_PLAYER            0x01u
#define DMS_ACTOR_GROUP_ENEMY             0x02u
#define DMS_ACTOR_GROUP_PLAYER_PROJECTILE 0x04u
#define DMS_ACTOR_GROUP_ENEMY_PROJECTILE  0x08u
#define DMS_ACTOR_GROUP_OBJECT            0x10u

typedef struct {
    uint16_t animation_id;
    uint16_t first_frame;       /* direct DRES frame for legacy/manual resources */
    uint16_t frame_count;       /* consecutive frames, 0 when animation_id is used */
    uint16_t duration_ticks;
    uint16_t sfx_enter, sfx_exit;
    uint8_t loop;
    uint8_t gravity;
    uint8_t collision_world;
    uint8_t controllable;
    uint8_t flags;
    int16_t speed_mul_q8;
    int16_t animation_speed_q8;
} DmsActorStateDesc;

typedef struct {
    uint16_t source_state, dest_state;
    uint8_t condition, op, action, button_mask;
    int16_t value_q8;
    uint8_t priority;
} DmsActorTransitionDesc;

typedef struct {
    uint16_t state;
    int16_t knockback_x_q8, knockback_y_q8;
    uint16_t stun_ticks, cooldown_ticks;
    uint8_t damage, target_mask, flags;
} DmsActorAttackDesc;

typedef struct {
    uint16_t actor_resource_id;
    uint16_t state;
    uint16_t cadence_ticks, life_ticks;
    int16_t speed_q8, offset_x, offset_y;
    uint8_t max_simultaneous, damage, group_mask, flags;
} DmsActorProjectileDesc;

typedef struct {
    uint16_t resource_id;
    uint16_t sprite_resource_id;
    uint16_t collision_resource_id;
    const DmsActorStateDesc *states;
    const DmsActorTransitionDesc *transitions;
    const DmsActorAttackDesc *attacks;
    const DmsActorProjectileDesc *projectiles;
    uint16_t state_count, transition_count, attack_count, projectile_count, initial_state;
    int16_t max_vx_q8, max_vy_q8;
    int16_t accel_x_q8, accel_y_q8, brake_x_q8, brake_y_q8;
    int16_t gravity_q8, max_fall_q8, jump_vy_q8;
    int16_t received_knockback_x_q8, received_knockback_y_q8;
    int16_t ai_patrol_speed_q8;
    uint16_t hp_max, hp_start, invincibility_ticks, death_delay_ticks;
    uint16_t ai_detection_px, ai_loss_px, ai_patrol_distance_px, ai_decision_ticks;
    uint8_t player_controlled;
    uint8_t target_mask;
    uint8_t contact_damage;
    uint8_t death_destroys;
    uint8_t ai_mode;
    uint8_t ai_flags;
    uint8_t activation_margin;
    uint8_t offscreen_flags; /* bit0 active offscreen, bit1 destroy offscreen */
    uint8_t hurt_state;
    uint8_t death_state;
    uint8_t coyote_ticks;
    uint8_t jump_buffer_ticks;
    uint8_t jump_button_mask;
    uint8_t max_jumps;
    uint8_t movement_axis;
    uint8_t allow_diagonal;
    uint8_t respawn_on_danger;
} DmsActorResourceDesc;

#define DMS_SFX_SAMPLE_A 1u
#define DMS_SFX_SAMPLE_B 2u
#define DMS_SFX_FM 3u
#define DMS_SFX_SSG 4u
#define DMS_SFX_COMPOSITE 5u
#define DMS_AUDIO_STEAL 0u
#define DMS_AUDIO_IGNORE 1u
#define DMS_AUDIO_QUEUE 2u
#define DMS_AUDIO_FORCE 3u

typedef struct {
    uint16_t address;
    uint8_t value;
} DmsAudioRegWrite;

typedef struct {
    uint16_t id;
    uint16_t duration_frames;
    uint16_t start_page, end_page;
    uint16_t rate_hz;
    uint16_t program_first, program_count;
    uint16_t composite_first, composite_count;
    uint8_t kind, target, priority, conflict, duck_steps;
    uint8_t level, pan, flags;
} DmsSfxResourceDesc;

typedef struct {
    uint16_t id;
    uint16_t start_bank;
    uint16_t bank_count;
    uint8_t priorities[9];
} DmsMusicResourceDesc;

extern const DmsSpriteResourceDesc dms_sprite_resources[];
extern const uint16_t dms_sprite_resource_count;
extern const DmsDresResourceDesc dms_dres_resources[];
extern const uint16_t dms_dres_resource_count;
extern const DmsImageResourceDesc dms_image_resources[];
extern const uint16_t dms_image_resource_count;
extern const DmsMapResourceDesc dms_map_resources[];
extern const uint16_t dms_map_resource_count;
extern const DmsCollisionResourceDesc dms_collision_resources[];
extern const uint16_t dms_collision_resource_count;
extern const DmsActorResourceDesc dms_actor_resources[];
extern const uint16_t dms_actor_resource_count;
extern const DmsSceneResourceDesc dms_scene_resources[];
extern const uint16_t dms_scene_resource_count;
extern const DmsMusicResourceDesc dms_music_resources[];
extern const uint16_t dms_music_resource_count;
extern const DmsSfxResourceDesc dms_sfx_resources[];
extern const uint16_t dms_sfx_resource_count;
extern const DmsAudioRegWrite dms_sfx_program[];
extern const uint16_t dms_sfx_program_count;
extern const uint16_t dms_sfx_composite_members[];
extern const uint16_t dms_sfx_composite_member_count;
extern const uint8_t dms_music_channel_priorities[9];

/* Internal libdms helpers shared between subsystems. */
int16_t dms_bg_scroll_x(void);
int16_t dms_bg_scroll_y(void);
uint16_t dms_bg_pattern_limit(void);
uint16_t dms_bg_pattern_floor(void);
uint16_t dms_coll_world_width(void);
uint16_t dms_coll_world_height(void);
void dms_sprite_set_frame(uint16_t sprite, uint16_t frame_id);
uint16_t dms_sprite_get_frame(uint16_t sprite);
const DmsDresResourceDesc *dms_sprite_desc_for_handle(uint16_t sprite);
uint16_t dms_sprite_reserve_patterns(uint16_t pattern_count);

#endif
